# permissions to do edit asms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: asm-editor-role
rules:
- apiGroups:
  - operator.alauda.io
  resources:
  - asms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.alauda.io
  resources:
  - asms/status
  verbs:
  - get
  - patch
  - update
