# permissions to do viewer asms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: asm-viewer-role
rules:
- apiGroups:
  - operator.alauda.io
  resources:
  - asms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.alauda.io
  resources:
  - asms/status
  verbs:
  - get
